-- ============================================================================
-- Snowflake Platform Demo — Foundation Setup
-- Session 0: Warehouses, Databases, Schemas, Base Roles
-- ============================================================================
-- Idempotent: safe to re-run at any time.
-- Naming: BANKING_DEMO_* prefix (see snowflake-platform-demo/naming-conventions.md)
-- Execution: snowsql -f scripts/00_foundation.sql
-- ============================================================================

USE ROLE SECURITYADMIN;

-- ---------------------------------------------------------------------------
-- Roles
-- ---------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS BANKING_DEMO_SYSADMIN;
CREATE ROLE IF NOT EXISTS BANKING_DEMO_SECURITYADMIN;
CREATE ROLE IF NOT EXISTS BANKING_DEMO_ENGINEER;
CREATE ROLE IF NOT EXISTS BANKING_DEMO_BI_ANALYST;

-- Role hierarchy: demo roles inherit from SYSADMIN-equivalent custom role only
GRANT ROLE BANKING_DEMO_SYSADMIN    TO ROLE BANKING_DEMO_SECURITYADMIN;
GRANT ROLE BANKING_DEMO_ENGINEER    TO ROLE BANKING_DEMO_SYSADMIN;
GRANT ROLE BANKING_DEMO_BI_ANALYST  TO ROLE BANKING_DEMO_SYSADMIN;

-- ---------------------------------------------------------------------------
-- Warehouses
-- ---------------------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS BANKING_DEMO_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS BANKING_DEMO_TRANSFORM_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS BANKING_DEMO_ML_WH
    WITH WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS BANKING_DEMO_APP_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- ---------------------------------------------------------------------------
-- Databases
-- ---------------------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS BANKING_DEMO_DB;

-- ---------------------------------------------------------------------------
-- Schemas
-- ---------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS BANKING_DEMO_DB.RAW;
CREATE SCHEMA IF NOT EXISTS BANKING_DEMO_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS BANKING_DEMO_DB.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS BANKING_DEMO_DB.ML;
CREATE SCHEMA IF NOT EXISTS BANKING_DEMO_DB.GOVERNANCE;

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------
USE ROLE BANKING_DEMO_SECURITYADMIN;

GRANT USAGE ON DATABASE BANKING_DEMO_DB          TO ROLE BANKING_DEMO_SYSADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BANKING_DEMO_DB TO ROLE BANKING_DEMO_SYSADMIN;

GRANT USAGE ON WAREHOUSE BANKING_DEMO_WH           TO ROLE BANKING_DEMO_SYSADMIN;
GRANT USAGE ON WAREHOUSE BANKING_DEMO_TRANSFORM_WH TO ROLE BANKING_DEMO_SYSADMIN;
GRANT USAGE ON WAREHOUSE BANKING_DEMO_ML_WH        TO ROLE BANKING_DEMO_SYSADMIN;
GRANT USAGE ON WAREHOUSE BANKING_DEMO_APP_WH       TO ROLE BANKING_DEMO_SYSADMIN;

GRANT USAGE ON DATABASE BANKING_DEMO_DB               TO ROLE BANKING_DEMO_ENGINEER;
GRANT USAGE ON SCHEMA BANKING_DEMO_DB.RAW             TO ROLE BANKING_DEMO_ENGINEER;
GRANT USAGE ON SCHEMA BANKING_DEMO_DB.STAGING         TO ROLE BANKING_DEMO_ENGINEER;
GRANT CREATE TABLE ON SCHEMA BANKING_DEMO_DB.RAW      TO ROLE BANKING_DEMO_ENGINEER;
GRANT CREATE TABLE ON SCHEMA BANKING_DEMO_DB.STAGING  TO ROLE BANKING_DEMO_ENGINEER;
GRANT USAGE ON WAREHOUSE BANKING_DEMO_WH              TO ROLE BANKING_DEMO_ENGINEER;
GRANT USAGE ON WAREHOUSE BANKING_DEMO_TRANSFORM_WH    TO ROLE BANKING_DEMO_ENGINEER;

GRANT USAGE ON DATABASE BANKING_DEMO_DB            TO ROLE BANKING_DEMO_BI_ANALYST;
GRANT USAGE ON SCHEMA BANKING_DEMO_DB.ANALYTICS    TO ROLE BANKING_DEMO_BI_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA BANKING_DEMO_DB.ANALYTICS
    TO ROLE BANKING_DEMO_BI_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BANKING_DEMO_DB.ANALYTICS
    TO ROLE BANKING_DEMO_BI_ANALYST;
GRANT USAGE ON WAREHOUSE BANKING_DEMO_WH           TO ROLE BANKING_DEMO_BI_ANALYST;
